server:
  port: 8089
spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      datasource:
        master:
          url: jdbc:sqlite:D:\MyProject\spring-demo\sqlite.db
          driver-class-name: org.sqlite.JDBC
  redis:
    database: 0
    host: 122.152.200.229 #Redis服务器地址
    port: 6379   # Redis服务器连接端口
    password: xlife123 # Redis服务器连接密码（默认为空）
    jedis:   # 连接池最大连接数（使用负值表示没有限制）
      pool:
        max-active: 8  #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms  # 连接池中的最大空闲连接
        max-idle: 8 # 连接池中的最小空闲连接
        min-idle: 0
        timeout: 0  # 连接超时时间（毫秒）
  session:
    timeout: 1800
logging:
  config: classpath:logback-boot.xml
mybatis-plus:
  mapper-locations:  classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  typeAliasesPackage:  com.example.demo.entity  # 注意：对应实体类的路径
  configuration:
    #默认开启
    mapUnderscoreToCamelCase: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



